on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
        # Optional: specify a custom build command if needed
        # build-command: 'npm install && npm run build'
        # Optional: specify the publish directory
        # publish-dir: './dist'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}